//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Arcelik_RCoS_v6 {
            get {
                object obj = ResourceManager.GetObject("Arcelik_RCoS_v6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ArcelikLogo {
            get {
                object obj = ResourceManager.GetObject("ArcelikLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (Simge) öğesine benzeyen System.Drawing.Icon türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Icon RCoSIcon {
            get {
                object obj = ResourceManager.GetObject("RCoSIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   /** @file       %FILENAMELC%.c
        /// *  @brief      %FILENAMEUC% application program file
        /// *  @copyright  (c) %YEAR%-Arcelik - All Rights Reserved
        /// *              Permission to use, reproduce, copy, prepare derivative works,
        /// *              modify, distribute, perform, display or sell this software and/or
        /// *              its documentation for any purpose is prohibited without the express
        /// *              written consent of Arcelik A.S.
        /// *  @author     %AUTHOR%
        /// *  @date       %DATE%
        /// */
        ///#define FILE_%FI [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tempApp_c {
            get {
                return ResourceManager.GetString("tempApp_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /** @file       %FILENAMELC%.h
        /// *  @brief      %FILENAMEUC% application header file
        /// *  @copyright  (c) %YEAR%-Arcelik - All Rights Reserved
        /// *              Permission to use, reproduce, copy, prepare derivative works,
        /// *              modify, distribute, perform, display or sell this software and/or
        /// *              its documentation for any purpose is prohibited without the express
        /// *              written consent of Arcelik A.S.
        /// *  @author     %AUTHOR%
        /// *  @date       %DATE%
        /// */
        ///#ifndef FILE_%FIL [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tempApp_h {
            get {
                return ResourceManager.GetString("tempApp_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /** @file       rcos.c
        /// *  @brief      RCoS+ main file
        /// *  @copyright  (c) %YEAR%-Arcelik - All Rights Reserved
        /// *              Permission to use, reproduce, copy, prepare derivative works,
        /// *              modify, distribute, perform, display or sell this software and/or
        /// *              its documentation for any purpose is prohibited without the express
        /// *              written consent of Arcelik A.S.
        /// *  @author     %AUTHOR%
        /// *  @date       %DATE%
        /// */
        ///#define FILE_RCOS_C
        ///
        ///#include &quot;rcos.h&quot;
        ///
        ///#d [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tempRCoS_c {
            get {
                return ResourceManager.GetString("tempRCoS_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /** @file       rcos.h
        /// *  @brief      RCoS+ configuration file
        /// *  @copyright  (c) %YEAR%-Arcelik - All Rights Reserved
        /// *              Permission to use, reproduce, copy, prepare derivative works,
        /// *              modify, distribute, perform, display or sell this software and/or
        /// *              its documentation for any purpose is prohibited without the express
        /// *              written consent of Arcelik A.S.
        /// *  @author     %AUTHOR%
        /// *  @date       %DATE%
        /// */
        ///#ifndef FILE_RCOS_H
        ///#define FILE_RCO [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tempRCoS_h {
            get {
                return ResourceManager.GetString("tempRCoS_h", resourceCulture);
            }
        }
    }
}
